### ISSUE TITLE
Switch to OSM instead of Google?

### ISSUE THREAD

**Issue by sergei-maertens** [VNG-Realisatie/gemma-zaken-demo#2]
Want... gratis enzo.

**Comment by joeribekker** [comment]
Sinds deze app alleen voor demonstratie doeleinden is, en het gratis-limiet van de Google APIs nog lang niet benaderd wordt zie ik geen noodzaak om dit wijzigen.

Wel eens dat het handiger is om een altijd-gratis map oplossing te gebruiken dus ik verwelkom een PR die die vervangt. Mocht het een probleem worden, dan graag nieuwe issue.

**Comment by i81b4u** [comment]
Het gaat mij niet zo zeer om het feit dat het gratis is, maar wil wel graag de privacy van gebruikers zo goed als mogelijk beschermen. Dat maakt het gebruik van diensten van Google ietwat omstreden om het maar mild te formuleren. Voor de demo misschien niet zo'n groot issue, maar ...

**Comment by joeribekker** [comment]
Zoals gezegd:

> dus ik verwelkom een PR die die vervangt.

en

> Mocht het een probleem worden, dan graag nieuwe issue.
