### ISSUE TITLE
Content-Security-Policy

### ISSUE THREAD

**Issue by i81b4u** [VNG-Realisatie/gemma-zaken-demo#22]
Het gebruik van een CSP wordt vandaag de dag ten zeerste aangeraden om de veiligheid van de gebruikers van webapplicaties beter te kunnen borgen. De CSP voor gebruik bij gemma-zaken-demo bevat verschillende elementen, zoals unsafe-inline, die de effectiviteit van de CSP enorm beperkt. Graag aandacht hiervoor bij het ontwikkelen van code. Als het wijzigen van de code zelf niet eenvoudig is, misschien is het dan een idee om een nonce-mechanisme te implementeren?

**Comment by michielverhoef** [comment]
Beste i81b4u, 

Het doel van de gemma-zaken-demo applicatie is niet een productiewaardige, secure oplossing te bieden. Het doel is in een afgeschermde omgeving gebruik van de door VNG ontwikkelde API standaarden voor het Zaakgericht werken te demonstreren. Zie voor meer toelichting hierop de readme.rst (https://github.com/VNG-Realisatie/gemma-zaken-demo/blob/master/README.rst).

In het verlengde daarvan is ook productie-gebruik van de referentieimplementaties waar deze demo applicatie gebruik van maakt niet toegestaan. Zie hiervoor de gebruiksvoorwaarden, vinden op https://zaakgerichtwerken.vng.cloud/beheer/gebruiksvoorwaarden

De in de issues genoemde risico's zijn ongetwijfeld van toepassing bij een implementatie van productiewaardige applicatie maar niet bij dit code voorbeeld. Ik sluit daarom deze issues.
