### ISSUE TITLE
Cookies zonder HttpOnly, Secure en sameSite

### ISSUE THREAD

**Issue by i81b4u** [VNG-Realisatie/gemma-zaken-demo#23]
De cookies die worden gezet bevatten geen kenmerken HttpOnly, Secure of sameSite. Kunnen die waar nodig worden gezet?

**Comment by michielverhoef** [comment]
Beste i81b4u,

Het doel van de gemma-zaken-demo applicatie is niet een productiewaardige, secure oplossing te bieden. Het doel is in een afgeschermde omgeving gebruik van de door VNG ontwikkelde API standaarden voor het Zaakgericht werken te demonstreren. Zie voor meer toelichting hierop de readme.rst (https://github.com/VNG-Realisatie/gemma-zaken-demo/blob/master/README.rst).

In het verlengde daarvan is ook productie-gebruik van de referentieimplementaties waar deze demo applicatie gebruik van maakt niet toegestaan. Zie hiervoor de gebruiksvoorwaarden, vinden op https://zaakgerichtwerken.vng.cloud/beheer/gebruiksvoorwaarden

De in de issues genoemde risico's zijn ongetwijfeld van toepassing bij een implementatie van productiewaardige applicatie maar niet bij dit code voorbeeld. Ik sluit daarom deze issues.
