### ISSUE TITLE
Reflected Cross Site Scripting kwetsbaarheden

### ISSUE THREAD

**Issue by i81b4u** [VNG-Realisatie/gemma-zaken-demo#24]
Het lijkt erop dat /apps/opendata/ met een POST van latitude en longitude last heeft van een reflected cross site scripting kwetsbaarheid. Getest met OWASP ZAP 2.8.0.

**Comment by michielverhoef** [comment]
Beste i81b4u,

Het doel van de gemma-zaken-demo applicatie is niet een productiewaardige, secure oplossing te bieden. Het doel is in een afgeschermde omgeving gebruik van de door VNG ontwikkelde API standaarden voor het Zaakgericht werken te demonstreren. Zie voor meer toelichting hierop de readme.rst (https://github.com/VNG-Realisatie/gemma-zaken-demo/blob/master/README.rst).

In het verlengde daarvan is ook productie-gebruik van de referentieimplementaties waar deze demo applicatie gebruik van maakt niet toegestaan. Zie hiervoor de gebruiksvoorwaarden, vinden op https://zaakgerichtwerken.vng.cloud/beheer/gebruiksvoorwaarden

De in de issues genoemde risico's zijn ongetwijfeld van toepassing bij een implementatie van productiewaardige applicatie maar niet bij dit code voorbeeld. Ik sluit daarom deze issues.

**Comment by sergei-maertens** [comment]
Deze is toch ernstig genoeg om op te pakken door het publieke karakter van de gehoste APIs voor testdoeleinden. Wordt gefixed.

**Comment by sergei-maertens** [comment]
Fixed in 41acbc67fb93aa1e6c7a20bea92cbda5a3a96815

**Comment by sergei-maertens** [comment]
En gedeployed.
