### ISSUE TITLE
Zaakdetail demo -> zaaktype moet URL ophalen en niet geconfigureerde catalogus ID gebruiken

### ISSUE THREAD

**Issue by sergei-maertens** [VNG-Realisatie/gemma-zaken-demo#4]
Relevante code: https://github.com/VNG-Realisatie/gemma-zaken-demo/blob/master/src/zac/demo/zaakbeheer/views.py#L134

De gemma-zds-client ondersteunt tegenwoordig een `url` parameter zodat je niet de path parameters hoeft te extracten.

**Comment by joeribekker** [comment]
Dit kan niet zomaar... We hebben immers geen autorisatie-gegevens van een willekeurige URL...

**Comment by sergei-maertens** [comment]
Ik ga toch moeten kijken voor een oplossing, want het maakt het gebruik tegen ZTC eigenlijk praktisch onmogelijk...

**Comment by joeribekker** [comment]
Je kan ondertussen andere ZTC's configureren in de Demo app. Als je deze configureert kan je de Zaaktypen van andere ZTCs ophalen.
